# Generated by Django 5.2.4 on 2026-03-30 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="HoldType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cdn_ref", models.CharField(max_length=20, unique=True)),
                ("manufacturer", models.CharField(default="unknown", max_length=200)),
                ("model", models.CharField(default="unknown", max_length=200)),
                ("size", models.CharField(default="unknown", max_length=100)),
                (
                    "hold_usage_type",
                    models.CharField(
                        choices=[
                            ("hold", "Hold"),
                            ("volume", "Volume"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("available_colors", models.JSONField(default=list)),
                ("color_of_scan", models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="HoldInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "usage_type",
                    models.CharField(
                        choices=[("hold", "Hold"), ("volume", "Volume")],
                        default="hold",
                        max_length=20,
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hold_instances",
                        to="gym.gym",
                    ),
                ),
                (
                    "hold_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="gym.holdtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("cdn_ref", models.CharField(blank=True, max_length=500)),
                ("glb_file", models.FileField(blank=True, upload_to="walls/")),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walls",
                        to="gym.gym",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_name", models.CharField(max_length=200)),
                ("layout", models.TextField(blank=True)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="gym.gym",
                    ),
                ),
                (
                    "holds_collection",
                    models.ManyToManyField(
                        blank=True, related_name="sessions", to="gym.holdinstance"
                    ),
                ),
                (
                    "wall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="gym.wall",
                    ),
                ),
            ],
        ),
    ]
